### ISSUE TITLE
Spec editor signoff

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-global#10]
Once https://github.com/tc39/proposal-global/issues/9 is complete, part of the stage 2 → stage 3 requirements are that the spec editor has signed off.
- [x] @bterlson

**Comment by bterlson** [comment]
Seems good. Probably "global object" should be a dfn in main 262.

**Comment by ljharb** [comment]
@bterlson is that a change that should be reflected in this proposal's spec text?

**Comment by michaelficarra** [comment]
That would be a good idea.

**Comment by ljharb** [comment]
It looks like one already exists? https://tc39.github.io/ecma262/#global-object

**Comment by michaelficarra** [comment]
That's not the best `<dfn>`, but yes, it exists.

**Comment by ljharb** [comment]
Suggestions welcome if you'd like me to improve it in this spec - but my hope had been that this proposal wouldn't need to alter anything about what the global object is, merely provide a way to access it :-) if possible, i'd prefer to improve the definition in a direct PR to the spec rather than as part of this proposal.

**Comment by ljharb** [comment]
Reopening, pending #9.

**Comment by bterlson** [comment]
:shipit:
