### ISSUE TITLE
Document detailed naming research

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-global#11]
Document cases where using `self`, `window`, or `global` would break code that is currently using it for environment detection.

**Comment by ljharb** [comment]
There's a number of examples of `window` and `self` both implying a browser, such as  https://github.com/Microsoft/automatic-graph-layout/blob/ab371280000f4d85eeedc1899e6faaa66ccad009/GraphLayout/MsaglSharpkit/WebMsagl/Msagl/sharpkit_pre.js . In addition, `var self = this` is too common a pattern for `self` to be a safe bet.

---

`global` is a bit less problematic, since `browserify` automatically transpiles `global` to `window`, but here are some example places where `global` implies node, and node globals like `module`, `process`, etc:
- https://github.com/tyskdm/codegs-core/blob/18915f51a1f4de94a4412491b399104d07305aca/code/gas/global.js
- https://github.com/SilentCicero/string.js/blob/f8a052d5cb8375ce6eebfb7eeccb206ab5a8ef90/package-init.js
- https://github.com/noons-hackathon/node-elevator/blob/130ee5a2b244b3a5e0a51d2ba19066b2599c2b3d/floor.js
- https://github.com/sundalei/learnJS/blob/fde94f991f543e44949a0b09c421eaa92ec81521/node/test.js
- https://github.com/jamesmorgan/ethertel/blob/e75603d29c6fdffb91df045ae32f127ccd305875/app/lib/web3/package-init.js

**Comment by ljharb** [comment]
For posterity, a twitter poll: https://twitter.com/ljharb/status/734450903059570688

**Comment by pladaria** [comment]
Can this be re-opened? 

To me there are no strong reasons to discard `self`.

> There's a number of examples of window and self both implying a browser, such as...

Could you provide a list of those examples? (provided example makes no usage of self). If those examples run in backend, to me that's a minor issue.

> var self = this

I've never seen that in modern (ES6+) JS

---

Pro `self` reasons:
* Already exists in browsers, `self === window`. No breaking changes possible.
* `self` is the global object in web workers / service workers

From [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/self): 
> By using self, you can refer to the global scope in a way that will work not only in a window context (self will resolve to window.self) but also in a worker context (self will then resolve to WorkerGlobalScope.self).

So, looks like making `self === global` in node (or other non-browser runtimes) is the next logical step.

**Comment by kleinfreund** [comment]
@pladaria A list of examples is provided in https://github.com/tc39/proposal-global/issues/11#issuecomment-220802575.

> I've never seen that in modern (ES6+) JS

I see `var self = this;` all the time. As for sites that would break, there is a substantial number of live examples that demonstrate this; hence, it is not being considered anymore.

**Comment by j-f1** [comment]
@kleinfreund Creating a `self` variable shouldn’t cause an issue since the `self` will shadow the global `self`. Again, `self` already exists on the web, just not on Node.

**Comment by obedm503** [comment]
I agree with @j-f1. if a variable self is defined as something else, js already treats it as normal. Scoping rules apply as usual.

![image](https://user-images.githubusercontent.com/9118707/49305709-9d3b1700-f495-11e8-8c00-fb89c3d09602.png)

however, the problem is with node scripts that assume a browser environment if `self` exists.
