### ISSUE TITLE
polyfill VS native: possible enhancement

### ISSUE THREAD

**Issue by WebReflection** [tc39/proposal-global#2]
I wonder if, in case `System` is missing, it wouldn't be better to reflect a native descriptor.

``` js
if (typeof System !== 'object') {
  Object.defineProperty(global, 'System', {
    configurable: true,
    writable:  true,
    value: {}
  });
}
```

Moreover, I believe the `global` property in the `System` should actually throw if reassigned or, at least, be a constant, like the `PI` in the `Math` object.

``` js
if (!System.global) {
  Object.defineProperty(Symbol, 'global', {value: global});
}
```

What do you think?

**Comment by ljharb** [comment]
The "polyfill" in the proposal repo is an example implementation and isn't meant to be consumed, simply a reference implementation.

Once the naming issue is resolved, I'll release a module on npm that uses `define-properties` to do exactly as you suggest.
