### ISSUE TITLE
Was "Global" name taken in consideration for naming?

### ISSUE THREAD

**Issue by micnic** [tc39/proposal-global#30]
I hope I am not late for the party, I read that the `global` name can't be used as it will break the web, but I was interested if `Global`, with the first capital letter, was taken in consideration for naming in this proposal?

**Comment by ljharb** [comment]
Yes, it was considered as one of the options, but it was generally disliked due to sharing the PascalCase naming convention with constructors and namespaces.

The time for considering alternatives is indeed long past; the name has been selected.
