### ISSUE TITLE
How about `standard` and `std` ?

### ISSUE THREAD

**Issue by blfunex** [tc39/proposal-global#37]
I read the NAMING file and didn't find constraints related to this name.
My rationale is that the global object provides the standard ECMAScript types to the user.

**Comment by aciccarello** [comment]
Wouldn't it also have references to non-standard variables defined globally?

**Comment by ljharb** [comment]
Thanks! That’s definitely a new suggestion.

There’s a current proposal, https://github.com/tc39/proposal-javascript-standard-library , that might create a world where new standard types wouldn’t need to be on the global - additionally, there’s many builtin types that are not on the global (AsyncFunction, for example).

(As for “std”; i don’t think abbreviations are helpful, nor do i think we should select abbreviations that have easily misappropriated alternate definitions when we can avoid it)

**Comment by codehag** [comment]
Thanks for the suggestion @blfunex !

If it didn't conflict with the standard library proposal it would be a great candidate :/ I agree with ljharb regarding abbreviations -- and to top it off, that abbreviation is also proposed for the standard library. If you have other ideas please let us know.

Let us know if you have any further questions. If everything is clear, let us know and I will close this. Further suggestions are very welcome.

**Comment by ljharb** [comment]
Closing; happy to reopen if needed.
