### ISSUE TITLE
Polyfill does not work in an ES module context

### ISSUE THREAD

**Issue by rictic** [tc39/proposal-global#43]
When running as an ES Module, the global `this` is always undefined.

**Comment by rictic** [comment]
The best version I've got:

```javascript
var polyfilledGlobalThis = 
  this !== undefined ? this :
  typeof window === 'object' ? window : 
  typeof global === 'object' ? global : 
  undefined /* or maybe throw? */;
```

**Comment by ljharb** [comment]
`Function(‘return this’)()` absolutely works in an ES Module context.

Ether way, proposal repo polyfills aren’t for production use. Use https://npmjs.com/globalthis
