### ISSUE TITLE
System.environment

### ISSUE THREAD

**Issue by petamoriken** [tc39/proposal-global#5]
Although I might not it should make the issue here, I want to hear this.
I suggest that `System.environment` should return environment string.

i.e.
in Browser: `System.environment === "Browser"`
in WebWorker: `System.environment === "Worker"`
in Node: `System.environment === "Node"`

Actually we must write below:

``` javascript
if(typeof window === "object") {
  // Browser
} else if(typeof importScripts === "function") {
  // WebWorker
} else if(typeof process === "object") {
  // Node
}
```

**Comment by ljharb** [comment]
What would `node-webkit`/`electron` return, which is both "node" and "browser"? What would an engine that is none of these three return, like `jsc` or Adobe Photoshop?

Describing the environment would be virtually impossible to specify reliably, would be dangerous to provide underspecified, and is not related to this proposal.
